### ISSUE TITLE
Need create "How to make PR.md"

### ISSUE THREAD

**Issue by bots-business** [bots-business/BBExpertsList#10]
Need create "How to make PR.md" - how to add PR for new Expert
It must be howto for newbie.

Reward: 1-10 ELM, 1-10 MLP

**Comment by killerbhai** [comment]
Make a new file put your msg there then upload it here and then commit changes

**Comment by sohamdeogaonkar** [comment]
sir do we want to add pull request to same files

because  they may try to change others level too.
if u accepted it in hurry

can we ask to pull request there details by creating new files
and you copy and paste that data

i think it will secure

**Comment by bots-business** [comment]
> Need create "How to make PR.md" - how to add PR for new Expert
> It must be howto for newbie.
> 
> Reward: 1-10 ELM, 1-10 MLP

Task desc updated

**Comment by bots-business** [comment]
> sir do we want to add pull request to same files
> 
> because they may try to change others level too.
> if u accepted it in hurry
> 
> can we ask to pull request there details by creating new files
> and you copy and paste that data
> 
> i think it will secure

Yes. It is good idea. 
But I think we just need 1-3 Trusted Expert for merging.
This Experts can validate data and make merge.
