### ISSUE TITLE
ELP, MLP names

### ISSUE THREAD

**Issue by bots-business** [bots-business/BBExpertsList#11]
I think Expert Level (EL) and Master Level - (ML) is better?

How do you think?

**Comment by killerbhai** [comment]
Good

**Comment by killerbhai** [comment]
Make it ELP and MLP

**Comment by mohdradin** [comment]
ML

**Comment by adebello04** [comment]
I think it good

**Comment by DevAmanSingh** [comment]
El expert level 
And ml master level 
I am coderninja

**Comment by bots-business** [comment]
EL + ML - renamed
