### ISSUE TITLE
BB Expert chat

### ISSUE THREAD

**Issue by bots-business** [bots-business/BBExpertsList#2]
Base64:
aHR0cHM6Ly90Lm1lL2pvaW5jaGF0Ly0yUFFWQWgxUDQ0NE5qa3k=

**Comment by bots-business** [comment]
Hint after hour.
Reward will be reduced

**Comment by charchit123125** [comment]
What is the issu ??

**Comment by Fantasyverse** [comment]
Which issue i have to solve

**Comment by Fantasyverse** [comment]
> Base64:
> aHR0cHM6Ly90Lm1lL2pvaW5jaGF0Ly0yUFFWQWgxUDQ0NE5qa3k=2

**Comment by bots-business** [comment]
It is just Base64 you need to decode this

**Comment by killerbhai** [comment]
https://t.me/joinchat/-2PQVAh1P444Njky6

**Comment by killerbhai** [comment]
https://t.me/joinchat/-2PQVAh1P444Njky


Admin is this correct

**Comment by killerbhai** [comment]
Sir I am enter on the BB expert group
![Uploading Screenshot_2021-05-20-13-01-52-10_1149b56b894fd37d9a6fe46f85aae740.jpg…]()

**Comment by bots-business** [comment]
We have only 2 members in BB Expert chat!

**Comment by mohdradin** [comment]
> Base64:
> aHR0cHM6Ly90Lm1lL2pvaW5jaGF0Ly0yUFFWQWgxUDQ0NE5qa3k=

what i need to do with this

**Comment by mohdradin** [comment]
> aHR0cHM6Ly90Lm1lL2pvaW5jaGF0Ly0yUFFWQWgxUDQ0NE5qa3k=2

expired

**Comment by ShadabAlam786** [comment]
Joined
