### ISSUE TITLE
I am not there pls add me

### ISSUE THREAD

**Issue by killerbhai** [bots-business/BBExpertsList#31]
I am not there pls add me my name :- Phsyco AJ username :- @PhsycoAJ

**Comment by bots-business** [comment]
We need PR for this Expert

EL - 0.5

**Comment by Untoldhacker-Dev** [comment]
Edit Readme file and add your name (create pull request)

**Comment by bots-business** [comment]
simular task - https://github.com/bots-business/BBExpertsList/issues/32
