### ISSUE TITLE
I am Not In List Please Add Me Too

### ISSUE THREAD

**Issue by mohdradin** [bots-business/BBExpertsList#32]

**Comment by bots-business** [comment]
Need your Telegram nickname

We need PR for this Expert

EL - 0.5

**Comment by sohamdeogaonkar** [comment]
please send your name and telegram username

**Comment by sohamdeogaonkar** [comment]
@bots-business 
we cant do anything

if he didnt reply
it is acquiring the issue space

**Comment by bots-business** [comment]
Try to ask in BB Expert Chat

**Comment by mohdradin** [comment]
> please send your name and telegram username

@Radin_X

**Comment by bots-business** [comment]
solved - https://github.com/bots-business/BBExpertsList/pull/39
