### ISSUE TITLE
Logo😳😁

### ISSUE THREAD

**Issue by rockey170** [bots-business/BBExpertsList#34]
![LogoMakerCa-1621515361009](https://user-images.githubusercontent.com/81092571/118982452-14800080-b999-11eb-935e-5fbfcb826ceb.png)

**Comment by bots-business** [comment]
So big? 
Tet will not be reading in small pic....

**Comment by bots-business** [comment]
https://github.com/bots-business/BBExpertsList/issues/25 use this task for posting

**Comment by Untoldhacker-Dev** [comment]
> So big?
> Tet will not be reading in small pic....

![20210520_181901](https://user-images.githubusercontent.com/74806602/118983867-84db5180-b99a-11eb-9401-cbe655dbb020.jpg)
