### ISSUE TITLE
Need update Total Expert Level in readme.md

### ISSUE THREAD

**Issue by sohamdeogaonkar** [bots-business/BBExpertsList#40]

**Comment by bots-business** [comment]
And what do you want? What the fix can be here?

**Comment by sohamdeogaonkar** [comment]
complete it

**Comment by sohamdeogaonkar** [comment]
@bots-business 

R THE EXPERT LEVCEL AND MASTER LEVEL IN REAMDE.md r for the fun

becaus ethere is no use of it.
we cant know who is top
with how many points

**Comment by bots-business** [comment]
yes it can be

**Comment by bots-business** [comment]
I make table - https://docs.google.com/spreadsheets/d/1XJca_WQBN4C-pGnOtzxhqeICzGaOR2tprSLzYL5vx_0/edit?usp=sharing

It is possible to calce total level for each Expert in easy way now

**Comment by sohamdeogaonkar** [comment]
> I make table - https://docs.google.com/spreadsheets/d/1XJca_WQBN4C-pGnOtzxhqeICzGaOR2tprSLzYL5vx_0/edit?usp=sharing
> 
> It is possible to calce total level for each Expert in easy way now

@bots-business 
but this  is just log list
where is the total expert and master level of every users

**Comment by ShadabAlam786** [comment]
There Is No Anywhere Written That Who Is In Which Level So We Can't Update It.
@bots-business

**Comment by bots-business** [comment]
@ShadabAlam786 
look on column header

![image](https://user-images.githubusercontent.com/38240269/119416565-44cbf400-bd37-11eb-92b9-a102245826a2.png)

**Comment by sohamdeogaonkar** [comment]
@bots-business 
But not done total yet
