### ISSUE TITLE
Logo For BB EXPERTS

### ISSUE THREAD

**Issue by mohdradin** [bots-business/BBExpertsList#45]
> ![images-02](https://user-images.githubusercontent.com/78489643/119129424-849f8c80-ba54-11eb-9f50-d2fe10201635.jpeg)
> How Is This Logo

**Comment by sohamdeogaonkar** [comment]
@mohdradin 
why u create new issue when there is already a issue about it

**Comment by sohamdeogaonkar** [comment]
Send your logo in that issue
